### ISSUE TITLE
No primary method: cl-generic-generalizers, (eql etags)

### ISSUE THREAD

**Issue by pyluyten** [jerry40/the-old-mode#5]
when required the old from init.el automatically, i have an error : 
No primary method: cl-generic-generalizers, (eql etags)

this is similar to this issue : 
https://github.com/k-talo/volatile-highlights.el/issues/15

The error does not happen when manually requiring the-old.
maybe i miss one dep which is loaded after init.
or, manually requiring a file would trigger something different.

in the-old.el i do not see cl.
it might be shr, which has
(eval-when-compile (require 'cl))

**Comment by jerry40** [comment]
Strange, it works for me... I have `(require 'the-old)` in my .emacs file. Perhaps init.el  differs from .emacs somehow?

**Comment by pyluyten** [comment]
i have 
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19)

(more precisely OS is arch linux.) Which version do you have?

**Comment by jerry40** [comment]
```
Linux MS-7721 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-20 on lcy01-07, modified by Debian
```

**Comment by pyluyten** [comment]
I found issue. The-old defines func like "filter" or "alist-get". I believe the library should always name its func the-old-filter, the-old-alist-get, and so on. So, i did add prefix to each the-old func and variable.

I do not have issue anymore. But my patch is not ready got master yet. Many things still work, but i noticed i have error messages with 2 kind of functions : marking (un)read and marking (un)starred. At first view the commit is fine - is is a simple "replace" , func-name => the-old-func-name 

Maybe you have an idea how to fix this part
[0001-Add-prefix-to-var-and-func.patch.txt](https://github.com/jerry40/the-old-mode/files/1451944/0001-Add-prefix-to-var-and-func.patch.txt)

**Comment by jerry40** [comment]
Wow, I'd never discover this bug :) Thanks a lot! Let me examine the patch , perhaps it would be better to chnange function names one-by-one (due to many cases)

**Comment by pyluyten** [comment]
well i can split commit but then expect something like 40 patches   ;)
in which case we'd better agree on best workflow before

**Comment by jerry40** [comment]
Could you commit your changes and we'll try to test the mode? I'm sure we can fix possible issues anyway.

**Comment by pyluyten** [comment]
sure, i just pushed a new branch, "namespace"

**Comment by jerry40** [comment]
I've merged `namespace` into `master`, thank you very much for your help!

**Comment by pyluyten** [comment]
ah cool it work for marking read thanks to your alist-get. I was suspecting this func but i could not solve the issue! also this explains why this broke stuff previously (redefining alist-get).

i still cannot mark unread / starred

attaching a cosmetic patch
[fix-typo-in-namespace-commit.txt](https://github.com/jerry40/the-old-mode/files/1464073/fix-typo-in-namespace-commit.txt)

**Comment by jerry40** [comment]
I've discovered the issue. 't' and 'u' keybindings are working well, but functions they use firstly check an article status (whether it is read or unread). And here is the problem - an article was loaded before toggling read/unread and haven't been refreshed after that. I've applied your patch and changed an option in order to load all articles (read and unread). So now you can test 't' this way:
- Load articles (g)
- Choose one, set it read or unread (t)
- Reload view (g)
- See changes (if any)

**Comment by pyluyten** [comment]
yes this works now , i think branch is ready for master (because last commit is still in keybinding branch)

**Comment by jerry40** [comment]
Perhaps changed article should be 
1) reread from the net 
2) reload in the view
It is possible to do it in async mode... I'll think about this

**Comment by pyluyten** [comment]
I think async is a big topic!

- maybe operations like r / s could mark articles, then one key would apply changes.
  like some other modes. The advantage would be to apply changes en-masse
- indeed if you can do stuff async it would help. and i know Emacs will one day bring threads so this should help too, i guess
- some feedback would be nice after articles are marked read / starred
  and also after feeds are loaded / relaoded

but all of this is not clear enough to me to write an issue ; and i bet this is not trivial code

**Comment by jerry40** [comment]
I've added feedback, now we can test it

**Comment by jerry40** [comment]
There are some bugs due to emacs lisp recursion limitations, fixing...

**Comment by jerry40** [comment]
Fixed.

**Comment by pyluyten** [comment]
i think issue might be closed now? if i was wrong sorry, please re-open
